# Generated by Django 5.1.2 on 2024-11-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(upload_to='file/'),
        ),
    ]
