# Generated by Django 5.1.2 on 2024-11-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0002_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
