# Generated by Django 5.1.2 on 2024-11-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0004_file_in_on_s3_file_is_on_local'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='in_on_s3',
            new_name='is_on_s3',
        ),
    ]
