"""
Django settings for user_authentication project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
import datetime

# from .settings import JAZZMIN_SETTINGS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f=npz2(++_n!ckjb59one8l73dy84pn2$=xt)4^gn2yo@jj!m_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", True)

ALLOWED_HOSTS = ["localhost"]

# Application definition
INSTALLED_APPS = [
    # 'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'authentication',
    'sync_bnb',
    's3',
    'core',
    'wallet',

    # 3rd-party packages
    'rest_framework',
    'storages',
    'django5_recaptcha_admin_login',
    'django5_recaptcha_admin_login.captcha',

]

'''
MIDDALWARES
'''
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.CheckTokenTypes',
]

ROOT_URLCONF = 'user_authentication.urls'

RECAPTCHA_PUBLIC_KEY = "6LdgDp4qAAAAABp8dkE-v_W_OeDcBimUz-t-LKLE"
RECAPTCHA_PRIVATE_KEY = "6LdgDp4qAAAAAHRBgmWkRCZuJWog8uYqkRHIQw28"

# RECAPTCHA_PUBLIC_KEY = os.getenv('RECAPTCHA_PUBLIC_KEY')
# RECAPTCHA_PRIVATE_KEY = os.getenv('RECAPTCHA_PRIVATE_KEY')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'user_authentication.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
'''
Database
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

'''
Django Jazzmin Template
'''
JAZZMIN_SETTINGS = {
    "site_logo": "admin_pannel/logo_admin_pannel.png",
}

'''
BEP-20 URL for explore bnb transactions
'''
BSC_SCAN_API_URL = os.environ.get("BSC_SCAN_API_URL", "https://api.bscscan.com/api")

'''
JWT CONFIGS
'''
AUTH_USER_MODEL = "authentication.User"
JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=10),
    'JWT_ALGORITHM': 'HS256',
    'JWT_ALLOW_REFRESH': True,
    'JWT_AUTH_HEADER_PREFIX': 'Bearer'
}

'''
RESTFRAMEWORK CONFIGS
'''
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'core.authentication.JSONWebTokenAuthentication',
    ),
    'EXCEPTION_HANDLER': 'core.authentication.custom_exception_handler',
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

'''
STATIC FILES
'''
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Adjust as needed
]
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators


'''
DJANGO VALIDATORS
'''
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/


'''
Language and Localization Settings
'''
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = os.environ["EMAIL_HOST"]
# EMAIL_PORT = os.environ["EMAIL_PORT"]
# EMAIL_HOST_USER = os.environ["EMAIL_HOST_USER"]
# EMAIL_HOST_PASSWORD = os.environ["EMAIL_HOST_PASSWORD"]
# EMAIL_USE_TLS = True


'''
EMAIL SERVICE CONFIG
'''
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# DEFAULT_FROM_EMAIL = "sandbox.smtp.mailtrap.io"
# EMAIL_PORT = 2525
# EMAIL_HOST_USER = "9aae632c7f7eb9"
# EMAIL_HOST_PASSWORD = "0006b9f01b2dee"
# EMAIL_USE_TLS = False
# EMAIL_USE_SSL = False
# EMAIL_TIMEOUT = 10

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "arianminooei@gmail.com"
EMAIL_PORT = 587  # 25 for non secure protocol or connections
EMAIL_HOST_PASSWORD = "kmjo mzxi bmfg snve"
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_TIMEOUT = 10

import certifi

SSL_CERT_FILE = certifi.where()

'''
CELERY CONFIG
'''
CELERY_BROKER_URL = "redis://localhost:6379/0"

'''
S3 Config
'''

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
    },
    "local": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"
    }
}

AWS_ACCESS_KEY_ID = "70CjjAKlsdk8Icgiqi2C"
AWS_SECRET_ACCESS_KEY = "PCHkPgwEITWbZNO6c6bSEaWKrztwqlue7dRrsjSS"
AWS_STORAGE_BUCKET_NAME = "pingi-bucket"
AWS_S3_ENDPOINT_URL = "http://localhost:9000"
AWS_S3_USE_SSL = False
AWS_S3_FILE_OVERWRITE = False

# Telegram
TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN", None)
