# Generated by Django 5.1.2 on 2025-01-11 07:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d2557b4a-ff5f-4da5-810a-68a8a5a16a12'), editable=False, primary_key=True, serialize=False),
        ),
    ]
